import os
import html
import logging
import json
import re
from typing import List, Dict, Any, TypedDict, Optional

from qdrant_client import QdrantClient
from ollama import Client as OllamaClient
from ingestion.embedder import DocRAFTEmbedder
from retrieval.reranker import DocRAFTReranker

from langgraph.graph import StateGraph, END

logger = logging.getLogger("docraft.agent")

# ── Import initialized clients from main to avoid double-instantiation locks ──
def get_qdrant() -> QdrantClient:
    import main  # noqa: PLC0415
    if main.qdrant_client is None:
        raise RuntimeError("QdrantClient has not been initialized in main lifespan yet.")
    return main.qdrant_client

def get_ollama() -> OllamaClient:
    import main  # noqa: PLC0415
    if main.ollama_client is None:
        main.ollama_client = OllamaClient(host=os.getenv("OLLAMA_HOST", "http://127.0.0.1:11434"))
    return main.ollama_client

def get_embedder() -> DocRAFTEmbedder:
    import main  # noqa: PLC0415
    if main.doc_embedder is None:
        raise RuntimeError("DocRAFTEmbedder has not been initialized in main lifespan yet.")
    return main.doc_embedder

def get_reranker() -> DocRAFTReranker:
    import main  # noqa: PLC0415
    if main.doc_reranker is None:
        raise RuntimeError("DocRAFTReranker has not been initialized in main lifespan yet.")
    return main.doc_reranker


# ── State Graph definition ───────────────────────────────────────────────────
class AgentState(TypedDict):
    query: str
    messages: List[Dict[str, str]]
    retrieved_chunks: List[Dict[str, Any]]
    draft_response: str
    critic_feedback: str
    iteration_count: int
    is_verified: bool
    document_filter: List[str]


# ── Parsing Utilities ────────────────────────────────────────────────────────
def parse_critic_response(response_text: str) -> tuple[bool, str]:
    """Extract and parse the JSON block generated by the Critic model."""
    try:
        # Look for a JSON block inside the model response
        match = re.search(r"\{.*\}", response_text, re.DOTALL)
        if match:
            data = json.loads(match.group(0))
            return bool(data.get("is_verified", False)), str(data.get("feedback", ""))
    except Exception as e:
        logger.warning(f"Failed to parse critic JSON: {e}")
        
    # Standard fallback substring search if JSON fails to parse
    lower_text = response_text.lower()
    if '"is_verified": true' in lower_text or "'is_verified': true" in lower_text:
        return True, ""
    
    # Extract any textual critique as fallback feedback
    return False, response_text.strip()


# ── Graph Nodes ──────────────────────────────────────────────────────────────
def check_is_conversational(query: str) -> bool:
    """Detect if the query is a simple greeting or general help Capability question."""
    import re
    query_clean = re.sub(r'[^\w\s]', '', query.lower()).strip()
    
    # Greetings
    greetings = {"hello", "hi", "hey", "hola", "greetings", "howdy", "good morning", "good afternoon", "good evening"}
    if query_clean in greetings:
        return True
        
    # Capabilites questions
    help_phrases = [
        "what can you do", 
        "who are you", 
        "what is your purpose", 
        "help me", 
        "how to use this",
        "hello what can you do",
        "can you help me"
    ]
    if any(phrase in query_clean for phrase in help_phrases):
        return True
        
    return False


def is_summarization_query(query: str) -> bool:
    """Detect if the query is asking for a general document summary or overview."""
    words = {
        "summarize", "summary", "overview", "findings", "concepts", 
        "about this", "outline", "abstract", "introduction"
    }
    query_lower = query.lower()
    return any(w in query_lower for w in words)


def retrieve_node(state: AgentState) -> Dict[str, Any]:
    """Node 1: Retrieve matching documents from Qdrant with BGE Reranker fallback."""
    logger.info("[Agent Loop] Retrieving documents...")
    qdrant = get_qdrant()
    
    query = state["query"]
    doc_filter = state.get("document_filter")
    
    # Skip retrieval entirely for general conversational greetings
    if check_is_conversational(query):
        logger.info("[Agent Loop] General conversational greeting detected. Skipping vector database retrieval.")
        return {"retrieved_chunks": []}
        
    embedder = get_embedder()
    
    # 1. Embed current query
    query_vector = embedder.embed_query(query)
    
    # 2. Build Qdrant metadata filters
    query_filter = None
    if doc_filter:
        from qdrant_client.http import models as qdrant_models
        if isinstance(doc_filter, str) and doc_filter.strip():
            query_filter = qdrant_models.Filter(
                must=[
                    qdrant_models.FieldCondition(
                        key="source_document",
                        match=qdrant_models.MatchValue(value=doc_filter)
                    )
                ]
            )
        elif isinstance(doc_filter, list) and len(doc_filter) > 0:
            query_filter = qdrant_models.Filter(
                must=[
                    qdrant_models.FieldCondition(
                        key="source_document",
                        match=qdrant_models.MatchAny(any=doc_filter)
                    )
                ]
            )

    # 3. Phase 1 Vector Retrieval
    from ingestion.config import RETRIEVAL_CANDIDATE_K, RETRIEVAL_RERANK_N
    search_result = qdrant.query_points(
        collection_name="docraft_knowledge",
        query=query_vector,
        query_filter=query_filter,
        limit=RETRIEVAL_CANDIDATE_K
    ).points
    
    # 4. Phase 2 Reranking
    results = []
    enable_reranker = os.getenv("ENABLE_RERANKER", "false").lower() == "true"
    
    if len(search_result) > 0:
        if enable_reranker:
            try:
                reranker = get_reranker()
                texts = [hit.payload.get("text", "") for hit in search_result]
                reranked = reranker.rerank(query, texts, top_n=RETRIEVAL_RERANK_N)
                for orig_idx, score in reranked:
                    if score >= -4.0:  # Reranker noise-floor threshold
                        hit = search_result[orig_idx]
                        results.append({
                            "id": hit.id,
                            "score": score,
                            "text": html.unescape(hit.payload.get("text", "")),
                            "display_text": hit.payload.get("display_text", ""),
                            "source_document": hit.payload.get("source_document") or hit.payload.get("filename"),
                            "image_path": hit.payload.get("image_path"),
                            "content_type": hit.payload.get("content_type", "text"),
                            "chunk_index": hit.payload.get("chunk_index")
                        })
            except Exception as err:
                logger.error(f"Reranking inside agent failed: {err}. Falling back to cosine scores.")
                enable_reranker = False
                
        if not enable_reranker:
            logger.info("[Agent Loop] Bypassing cross-encoder reranker for ultra-low latency (<50ms).")
            for hit in search_result[:RETRIEVAL_RERANK_N]:
                results.append({
                    "id": hit.id,
                    "score": hit.score,
                    "text": html.unescape(hit.payload.get("text", "")),
                    "display_text": hit.payload.get("display_text", ""),
                    "source_document": hit.payload.get("source_document") or hit.payload.get("filename"),
                    "image_path": hit.payload.get("image_path"),
                    "content_type": hit.payload.get("content_type", "text"),
                    "chunk_index": hit.payload.get("chunk_index")
                })
                
    # 5. Dual-Layer Fallback: Scroll the first 4 document chunks directly for overview/summarization
    # queries, or if the vector search yielded zero matches after reranking filters.
    if doc_filter and (len(results) == 0 or is_summarization_query(query)):
        logger.info("[Agent Loop] Summarization request or empty vector matches. Invoking fallback document-start scroll...")
        from qdrant_client.http import models as qdrant_models
        
        if isinstance(doc_filter, str) and doc_filter.strip():
            scroll_filter = qdrant_models.Filter(
                must=[
                    qdrant_models.FieldCondition(
                        key="source_document",
                        match=qdrant_models.MatchValue(value=doc_filter)
                    )
                ]
            )
        else:
            scroll_filter = qdrant_models.Filter(
                must=[
                    qdrant_models.FieldCondition(
                        key="source_document",
                        match=qdrant_models.MatchAny(any=doc_filter)
                    )
                ]
            )
            
        try:
            scroll_result, _ = qdrant.scroll(
                collection_name="docraft_knowledge",
                scroll_filter=scroll_filter,
                limit=4,
                with_payload=True,
                with_vectors=False
            )
            if scroll_result:
                # Discard zero-match noise and populate with logical starting chunks
                results = []
                sorted_points = sorted(
                    scroll_result,
                    key=lambda p: p.payload.get("chunk_index", 0) if p.payload else 0
                )
                for point in sorted_points:
                    results.append({
                        "id": point.id,
                        "score": 1.0,
                        "text": html.unescape(point.payload.get("text", "") if point.payload else ""),
                        "display_text": point.payload.get("display_text", "") if point.payload else "",
                        "source_document": point.payload.get("source_document") or point.payload.get("filename") if point.payload else "unknown",
                        "image_path": point.payload.get("image_path") if point.payload else None,
                        "content_type": point.payload.get("content_type", "text") if point.payload else "text",
                        "chunk_index": point.payload.get("chunk_index") if point.payload else None
                    })
                logger.info(f"[Agent Loop] Fallback scroll successfully retrieved {len(results)} header chunks.")
        except Exception as scroll_err:
            logger.error(f"Fallback Qdrant scroll failed: {scroll_err}")
            
    # 6. Context Window Expansion (Neighbor Retrieval)
    # To prevent boundary cutoff (e.g. title in chunk 12, body/rules in chunk 13),
    # we expand each match to include its preceding and succeeding chunk indices.
    if len(results) > 0 and not (doc_filter and is_summarization_query(query)):
        logger.info("[Agent Loop] Expanding retrieved chunks with context window (preceding/succeeding)...")
        by_doc = {}
        for r in results:
            doc = r["source_document"]
            if not doc:
                continue
            idx = r.get("chunk_index")
            if idx is None:
                continue
            if doc not in by_doc:
                by_doc[doc] = set()
            by_doc[doc].add(idx)
            # Add preceding index if not first chunk
            if idx > 0:
                by_doc[doc].add(idx - 1)
            by_doc[doc].add(idx + 1)
            
        expanded_results = []
        from qdrant_client.http import models as qdrant_models
        for doc, indices in by_doc.items():
            scroll_filter = qdrant_models.Filter(
                must=[
                    qdrant_models.FieldCondition(
                        key="source_document",
                        match=qdrant_models.MatchValue(value=doc)
                    ),
                    qdrant_models.FieldCondition(
                        key="chunk_index",
                        match=qdrant_models.MatchAny(any=list(indices))
                    )
                ]
            )
            try:
                scroll_res, _ = qdrant.scroll(
                    collection_name="docraft_knowledge",
                    scroll_filter=scroll_filter,
                    limit=len(indices) * 2,
                    with_payload=True,
                    with_vectors=False
                )
                if scroll_res:
                    sorted_points = sorted(
                        scroll_res,
                        key=lambda p: p.payload.get("chunk_index", 0) if p.payload else 0
                    )
                    for point in sorted_points:
                        expanded_results.append({
                            "id": point.id,
                            "score": 1.0,
                            "text": html.unescape(point.payload.get("text", "") if point.payload else ""),
                            "display_text": point.payload.get("display_text", "") if point.payload else "",
                            "source_document": point.payload.get("source_document") or point.payload.get("filename") if point.payload else "unknown",
                            "image_path": point.payload.get("image_path") if point.payload else None,
                            "content_type": point.payload.get("content_type", "text") if point.payload else "text",
                            "chunk_index": point.payload.get("chunk_index") if point.payload else None
                        })
            except Exception as scroll_err:
                logger.error(f"Context window expansion failed for {doc}: {scroll_err}")
                # Fallback to original results for this document
                expanded_results.extend([r for r in results if r["source_document"] == doc])
                
        if expanded_results:
            results = expanded_results
                
    return {"retrieved_chunks": results}


def check_is_code_request(query: str) -> bool:
    """Detect if the user query is asking for code implementation or programming."""
    import re
    words = set(re.findall(r'\b\w+\b', query.lower()))
    
    # We want to match code/programming requests specifically, not just "implementation"
    code_words = {
        "code", "function", "method", "class", "python", "javascript", "java", 
        "c++", "program", "def", "import", "lock"
    }
    
    # Check for direct phrases like "write a", "implement a", "how to write"
    query_lower = query.lower()
    phrases = ["write a", "implement a", "how to write", "how to implement", "coding task"]
    if any(phrase in query_lower for phrase in phrases):
        # But exclude if they just ask for conceptual rules or steps
        if "rules" in words or "steps" in words:
            return False
        return True
        
    return len(words.intersection(code_words)) > 0


def call_ollama_chat_with_fallback(ollama_client, model: str, messages: list, options: dict) -> str:
    """
    Calls ollama.chat with the primary model. If it fails with any exception
    (e.g., model not found or loading failure), falls back to 'qwen2.5-coder:7b'.
    """
    fallback_model = "qwen2.5-coder:7b"
    if model == fallback_model:
        response = ollama_client.chat(model=model, messages=messages, options=options)
        return response["message"]["content"]
        
    try:
        response = ollama_client.chat(model=model, messages=messages, options=options)
        return response["message"]["content"]
    except Exception as e:
        logger.warning(f"Ollama chat call failed on primary model '{model}': {e}. Trying fallback '{fallback_model}'...")
        try:
            response = ollama_client.chat(model=fallback_model, messages=messages, options=options)
            return response["message"]["content"]
        except Exception as fallback_err:
            logger.error(f"Fallback model '{fallback_model}' also failed: {fallback_err}")
            raise fallback_err


def generator_node(state: AgentState) -> Dict[str, Any]:
    """Node 2: Generate initial draft using the retrieved document context."""
    logger.info("[Agent Loop] Generating response draft...")
    ollama = get_ollama()
    query = state["query"]
    chunks = state["retrieved_chunks"]
    messages = state["messages"]
    
    is_conversational = check_is_conversational(query)
    
    if is_conversational:
        system_prompt = """You are DocRAFT, an enterprise-grade document analysis assistant.
Provide a friendly, helpful, and conversational response to the user's greeting or capability question.
Explain that you can help analyze uploaded documents, summarize findings, extract key concepts, write code, and verify facts.
Do NOT mention any missing contexts, and do NOT state that you could not find information. Provide a direct, friendly answer."""
    else:
        # Format retrieved document contexts cleanly
        if chunks:
            context_block = "\n\n---\n\n".join([
                f"[Document Context {i + 1}]\n{c['text'] or c['display_text']}"
                for i, c in enumerate(chunks)
            ])
        else:
            context_block = "No relevant documents found in the knowledge base."
            
        system_prompt = f"""You are DocRAFT, an enterprise-grade document analysis assistant.

CRITICAL RULES:
- Answer ONLY from the retrieved context below. NEVER invent, guess, or hallucinate any numbers, facts, or details. (Exception: For programming/coding tasks, you are expected to fully implement standard algorithmic logic using your programming knowledge, but keep specific constraints, terms, and variable definitions strictly grounded on the context).
- When the context contains specific numbers, percentages, or data, you MUST quote them EXACTLY as they appear.
- If the context does not contain the answer, say: "I could not find this information in the uploaded documents."
- Do NOT include any inline citations, reference brackets (e.g., "[Source 1]"), or source filenames in your response text.
- Do NOT mention any internal prompt labels (such as 'Document Context', 'Context 1', or 'Retrieved Context') in your response text.
- Write detailed, thorough, and exhaustive answers ONLY when the topic requires it. Focus strictly on the specific question asked. Do NOT dump irrelevant rules or adjacent sections of the context (like AppendEntries rules for follower timeouts) just to increase response length.
- Use Markdown formatting: headers, bullet points, code blocks, and tables.
- When the context contains a table, reproduce it exactly in Markdown table format.
- When expressing math, use $...$ for inline and $$...$$ for display equations.
- If the user requests a specific format (e.g., write code, brief notes), you MUST prioritize the user's formatting request.
- NO META-COMMENTARY: Output ONLY the direct answer. Do NOT include any meta-commentary, notes about citations, explanations of rules, references to how the question was answered, or system formatting instructions."""

        is_code = check_is_code_request(query)
        if is_code:
            system_prompt += """

CRITICAL CODE GENERATION RULES:
- You must output complete, production-ready code.
- NEVER use placeholders, TODO comments, or pass statements in the code block.
- Every branch of logic must be fully implemented. If you fail to write the complete comparisons, the system will crash.
- Do NOT use math delimiters (like $ or $$) inside programming code blocks.
- Do NOT add boilerplate or stub methods (like convert_to_follower) that are not requested by the user if they cannot be fully implemented."""
        else:
            system_prompt += """

CRITICAL CONCEPTUAL RULES:
- Do NOT generate programming code or functions unless explicitly asked. Provide clear, well-structured, textual/conceptual explanations using headers and bullet points."""

    # Sliding window of 5 history items
    clean_messages = messages[-5:] if messages else []
    if clean_messages and clean_messages[0].get("role") == "assistant":
        clean_messages = clean_messages[1:]
        
    model_name = os.getenv("MODEL_NAME", "ulysses")
    
    # Formulate Chat history payload
    chat_history = [{"role": "system", "content": system_prompt}]
    
    # Deduplicate in case the last history message already matches the current query
    history_to_append = clean_messages
    if clean_messages and clean_messages[-1].get("role") == "user" and clean_messages[-1].get("content") == query:
        history_to_append = clean_messages[:-1]
        
    for msg in history_to_append:
        chat_history.append({"role": msg["role"], "content": msg["content"]})
        
    if is_conversational:
        chat_history.append({"role": "user", "content": query})
    else:
        user_prompt_with_context = f"""USER REQUEST:
{query}

Please answer the request above using the retrieved document context below.
CRITICAL output constraints:
- Start directly with the answer content.
- Do NOT repeat, copy-paste, or carry over any previous assistant answers, headers, or rules from the chat history.
- Do NOT output any introductory or concluding meta-commentary.
- Output ONLY the clean factual answer.

--- Retrieved Context ---
{context_block}
--- End Context ---"""
        chat_history.append({"role": "user", "content": user_prompt_with_context})
        
    num_predict = 2048 if check_is_code_request(query) else 1024
    content = call_ollama_chat_with_fallback(
        ollama,
        model_name,
        chat_history,
        {
            "temperature": 0.0,
            "num_ctx": 16384,
            "num_predict": num_predict,
        }
    )
    
    return {"draft_response": content, "iteration_count": state.get("iteration_count", 0) + 1}


def critic_node(state: AgentState) -> Dict[str, Any]:
    """Node 3: Validate draft response against strict verification constraints."""
    logger.info("[Agent Loop] Auditing response draft...")
    query = state["query"]
    
    # Conversational greetings do not need fact verification
    if check_is_conversational(query):
        logger.info("[Agent Loop] Conversational query. Bypassing Critic verification.")
        return {"is_verified": True, "critic_feedback": ""}
        
    is_code = check_is_code_request(query)
    if not is_code:
        logger.info("[Agent Loop] Conceptual query. Bypassing Critic verification to guarantee single-pass response.")
        return {"is_verified": True, "critic_feedback": ""}
        
    draft = state["draft_response"]
    
    # Deterministic static analysis check for code completeness (bypass LLM critic if placeholder check fails)
    from typing import Tuple
    def verify_code_completeness(code_text: str) -> Tuple[bool, str]:
        import re
        code_blocks = re.findall(r"```python\s*(.*?)\s*```", code_text, re.DOTALL)
        if not code_blocks:
            return True, ""
        for code_block in code_blocks:
            if re.search(r"#\s*(?:todo|placeholder|implement|add comparison|compare logs|fill this in|fixme)", code_block, re.IGNORECASE):
                return False, "Code contains incomplete placeholder comments or TODOs (e.g. '# Implement...'). Every function must be fully implemented."
            if re.search(r"\bpass\b", code_block):
                return False, "Code contains incomplete 'pass' statements. Write the complete logic or state transitions instead of using 'pass'."
            if "..." in code_block:
                return False, "Code contains incomplete '...' (ellipsis) placeholders. Write the logic fully."
            if "$" in code_block:
                return False, "Code contains invalid LaTeX math delimiters ($ or $$) inside the programming block. Output only pure, valid Python code."
        return True, ""
        
    is_complete, code_feedback = verify_code_completeness(draft)
    if not is_complete:
        logger.info(f"[Agent Loop] Code completeness audit failed: {code_feedback}")
        return {"is_verified": False, "critic_feedback": code_feedback}
        
    ollama = get_ollama()
    draft = state["draft_response"]
    chunks = state["retrieved_chunks"]
    
    if chunks:
        context_block = "\n\n---\n\n".join([
            c['text'] or c['display_text']
            for c in chunks
        ])
    else:
        context_block = "No relevant documents found in the knowledge base."
    
    is_code = check_is_code_request(query)
    if is_code:
        audit_rules = """1. CODE COMPLETENESS: The code must be 100% complete. If there are any placeholders, comments indicating missing or incomplete logic (e.g., "# Compare logs here...", "# Add comparison here"), TODOs, ellipses (...), or pass statements, "is_verified" MUST be false.
2. INTERFACE COMPLIANCE: The code must strictly comply with all technical constraints in the user's prompt (e.g. if the user requests thread safety or locks, it must use them; if they request a specific return type or return tuple like "(current_term, vote_granted)", it must return exactly that format).
3. NO STATE HALLUCINATIONS: The code must not refer to or assume variables that do not exist or are not defined in the scope."""
    else:
        audit_rules = """1. ACCURACY: The response must strictly follow all facts in the retrieved context. No hallucinations or mixed-up facts. If the draft states something incorrect or conflicts with the context, "is_verified" MUST be false.
2. RELEVANCE & COMPLETENESS: The response must answer the user's query completely. Do NOT penalize the response for omitting parts of the retrieved context that are irrelevant to the user's specific query. If the query asks for specific rules (e.g., 'list all 5 rules'), the response must list exactly all of them as described.
3. NO PROMPT LEAKAGE: The response must not leak any system instructions or meta-commentary (e.g. do not discuss rules, audit feedback, validation constraints, or prompts)."""

    critic_prompt = f"""You are an automated response auditor. Your task is to review the drafted response against the retrieved document context and quality rules.

Retrieved Context Block:
{context_block}

THE DRAFTED RESPONSE TO AUDIT:
\"\"\"
{draft}
\"\"\"

THE ORIGINAL USER REQUEST:
\"\"\"
{query}
\"\"\"

AUDIT RULES:
{audit_rules}

Output your audit result in JSON format matching this schema:
{{
  "is_verified": false or true,
  "feedback": "A list of specific inaccuracies, hallucinations, or rule violations (e.g., 'Draft incorrectly states that candidates send AppendEntries instead of RequestVote') or empty if verified is true"
}}
Respond ONLY with the raw JSON block. Do not write anything else."""
    model_name = os.getenv("MODEL_NAME", "ulysses")
    
    try:
        content = call_ollama_chat_with_fallback(
            ollama,
            model_name,
            [{"role": "user", "content": critic_prompt}],
            {
                "temperature": 0.0,
                "num_ctx": 16384,
                "num_predict": 512,
            }
        )
        is_verified, feedback = parse_critic_response(content)
    except Exception as e:
        logger.error(f"Critic node execution failed: {e}")
        # Fail safe
        is_verified, feedback = True, ""
        
    logger.info(f"[Agent Loop] Audit verification status: {is_verified}")
    return {"is_verified": is_verified, "critic_feedback": feedback}


def refinement_node(state: AgentState) -> Dict[str, Any]:
    """Node 4: Rewrite response correcting any critic issues."""
    logger.info("[Agent Loop] Refining response based on critic feedback...")
    ollama = get_ollama()
    query = state["query"]
    draft = state["draft_response"]
    feedback = state["critic_feedback"]
    chunks = state["retrieved_chunks"]
    iteration = state.get("iteration_count", 0)
    
    if chunks:
        context_block = "\n\n---\n\n".join([
            c['text'] or c['display_text']
            for c in chunks
        ])
    else:
        context_block = "No relevant documents found in the knowledge base."

    system_instruction = """You are DocRAFT. Your task is to correct the previous draft using only the retrieved context and critic feedback.
CRITICAL output constraints:
- Output ONLY the clean user-facing response content.
- Start directly with the answer text/code.
- Do NOT include any introductory or concluding meta-commentary (e.g. do NOT say "The corrected response is:", "Here is the corrected draft:").
- Do NOT mention the critic, feedback, audit process, or quality rules."""

    is_code = check_is_code_request(query)
    if is_code:
        system_instruction += "\n- Output ONLY complete code starting directly with a markdown code block."
    else:
        system_instruction += "\n- Output ONLY clean markdown text. Start directly with the answer content."

    user_payload = f"""ORIGINAL USER REQUEST:
{query}

Retrieved Context:
{context_block}

PREVIOUS DRAFT:
\"\"\"
{draft}
\"\"\"

CRITIC AUDIT FEEDBACK:
\"\"\"
{feedback}
\"\"\""""

    prompt = f"""{system_instruction}

---
{user_payload}
---

Final Corrected Response:"""

    model_name = os.getenv("MODEL_NAME", "ulysses")
    # Switch to fallback model on final iterations if primary model is failing verification
    if iteration >= 2:
        logger.info(f"[Agent Loop] Critic rejected draft after {iteration} iterations. Switching refinement to fallback model 'qwen2.5-coder:7b' for final correction.")
        model_name = "qwen2.5-coder:7b"
    
    num_predict = 2048 if check_is_code_request(query) else 1024
    new_draft = call_ollama_chat_with_fallback(
        ollama,
        model_name,
        [{"role": "user", "content": prompt}],
        {
            "temperature": 0.0,
            "num_ctx": 16384,
            "num_predict": num_predict,
        }
    )
    return {"draft_response": new_draft, "iteration_count": iteration + 1}


# ── Routing Conditional logic ────────────────────────────────────────────────
def should_continue(state: AgentState) -> str:
    if state["is_verified"]:
        logger.info("[Agent Loop] Verification succeeded. Terminating graph.")
        return END
    if state["iteration_count"] >= 3:
        logger.info("[Agent Loop] Max iteration count reached. Terminating graph.")
        return END
    logger.info(f"[Agent Loop] Loop failed validation. Iteration: {state['iteration_count']}/3.")
    return "refine"


# ── Compile LangGraph ────────────────────────────────────────────────────────
workflow = StateGraph(AgentState)
workflow.add_node("retrieve", retrieve_node)
workflow.add_node("generate", generator_node)
workflow.add_node("critic", critic_node)
workflow.add_node("refine", refinement_node)

workflow.set_entry_point("retrieve")
workflow.add_edge("retrieve", "generate")
workflow.add_edge("generate", "critic")
workflow.add_conditional_edges(
    "critic",
    should_continue,
    {
        "refine": "refine",
        END: END
    }
)
workflow.add_edge("refine", "critic")

agent_app = workflow.compile()


def clean_final_response(text: str) -> str:
    """Helper to post-process and strip out LLM-generated meta-commentary/source citation declarations."""
    if not text:
        return text
        
    lines = text.split("\n")
    cleaned_lines = []
    
    meta_patterns = [
        r"based on (?:the )?(?:retrieved )?context",
        r"based on document context",
        r"retrieved context provides",
        r"retrieved context contains",
        r"answer is based on",
        r"response is based on",
        r"explicitly stated in document",
        r"explicitly states in document",
        r"strictly adheres to the retrieved context",
        r"without any inline citations",
        r"without reference brackets",
        r"note: this answer",
        r"user[- ]format override"
    ]
    
    import re
    for line in lines:
        is_meta = False
        for pat in meta_patterns:
            if re.search(pat, line, re.IGNORECASE):
                is_meta = True
                break
        if not is_meta:
            cleaned_lines.append(line)
            
    return "\n".join(cleaned_lines).strip()


# ── Public Invocator ─────────────────────────────────────────────────────────
def run_rag_agent(query: str, messages: List[Dict[str, str]], document_filter: Optional[List[str]] = None) -> Dict[str, Any]:
    """
    Invokes the Compiled LangGraph and returns the final verified response 
    along with the retrieved source citations.
    """
    initial_state = {
        "query": query,
        "messages": messages,
        "document_filter": document_filter or [],
        "retrieved_chunks": [],
        "draft_response": "",
        "critic_feedback": "",
        "iteration_count": 0,
        "is_verified": False
    }
    
    final_state = agent_app.invoke(initial_state)
    
    # Format and deduplicate sources, limiting to top 3 as requested by the user
    sources = []
    seen_texts = set()
    for c in final_state["retrieved_chunks"]:
        text_snippet = c["text"][:100]
        if text_snippet in seen_texts:
            continue
        seen_texts.add(text_snippet)
        sources.append({
            "id": c["id"],
            "score": c.get("score", 1.0),
            "text": c["text"],
            "display_text": c.get("display_text") or c["text"],
            "filename": c["source_document"],
            "source_document": c["source_document"],
            "image_path": c.get("image_path"),
            "content_type": c.get("content_type", "text")
        })
        if len(sources) >= 3:
            break

    return {
        "response": clean_final_response(final_state["draft_response"]),
        "sources": sources
    }
